### ISSUE TITLE
Music bot breaks with URL as first song.

### ISSUE THREAD

**Issue by ajmwagar** [ajmwagar/zora#12]
The bot adds the song to the queue but does not play it.

**Steps to reproduce**:
1. Enter voice chat
2. .play https://www.youtube.com/watch?v=pFcv4NIuqvU
3. No music starts to play

**Expected behaviour**:
1. Enter voice chat
2. .play https://www.youtube.com/watch?v=pFcv4NIuqvU
3. Music play from a bot.

When you start it with a search but then add the song with .play it works so it's just when you start the bot with a URL.

**Comment by nlaha** [comment]
This is caused by the music bot trying to call `playSong();` before the song is added to the queue. Something probably related to ytdl taking longer to get info than ytsearcher.

**Comment by nlaha** [comment]
see b1e06bf0b775ae2068a4bf01707ba2d89a1cbd69
