### ISSUE TITLE
Fix crashing caused by incomplete config.json

### ISSUE THREAD

**Issue by ajmwagar** [ajmwagar/zora#20]
If someone could wrap most functions in config.json it would be really helpful to keep the bot stable.

**Comment by nlaha** [comment]
plan on using hasOwnProperty for each serverconfig and userprofile to check if they have the keys from the defaultconfig and default profile.

**For Example:**
```node
var defaultprofile = {
  level: 1,
  xp: 0,
  zcoins: 100,
  VIP: false
};
```

in the foreach loop for every user in userprofiles:
```node
if (config.userprofiles && !config.userprofiles.hasOwnProperty(user)) {
  if (!config.userprofiles[user].hasOwnProperty(zcoins)) {
    // add zcoins property to the user profile
  }
}
```
this way, when it detects that a user in userprofiles exists but doesn't have zcoins, it adds zcoins to their profile

**Comment by nlaha** [comment]
See: https://github.com/ajmwagar/zora/tree/mogodb
