### ISSUE TITLE
move userprofiles into a separate file or database

### ISSUE THREAD

**Issue by nlaha** [ajmwagar/zora#22]
Currently we are putting everything into one file. That file doesn't scale well.

**Comment by ajmwagar** [comment]
May I suggest we use MongoDB, https://www.mongodb.com/ or https://mlab.com

**Comment by nlaha** [comment]
moved userprofiles into new json file, should be fine for a little while

**Comment by nlaha** [comment]
See: https://github.com/ajmwagar/zora/tree/mogodb
