### ISSUE TITLE
Problem with forbes

### ISSUE THREAD

**Issue by nlaha** [ajmwagar/zora#27]
doesn't work on server with large amount of userprofiles

**Comment by ajmwagar** [comment]
see #22

**Comment by nlaha** [comment]
We need to find a way to search 20k+ users quickly and sort them by zcoins... this issue could go on for a while. I've commented it out for now because it was breaking the bot

**Comment by nlaha** [comment]
See: [this article](https://medium.com/@jeanjacquesbagui/in-mongoose-sort-by-date-node-js-4dfcba254110)

**Comment by nlaha** [comment]
Fixed in aa41dcfe12781c4a1b79e918241a55e56573fb83
